name: Snyk Delta

on:
  push:
    branches:
      - 'feat-**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run snyk monitor
        uses: snyk/actions/python-3.10@master
        with:
          command: test
          args: --json --print-deps > output.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
      - name: Run snyk delta
        run: |
          curl -Lo ./snyk-delta https://github.com/snyk-tech-services/snyk-delta/releases/download/v1.8.2/snyk-delta-linux
          chmod +x ./snyk-delta
          ./snyk-delta --version
          ./snyk-delta --baselineOrg 406b5850-5861-44fb-8565-afba44c57472 --baselineProject f5af5760-9626-4b3d-9669-9fcb9568308f <<< $(cat output.json)
