name: Snyk Monitor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run Snyk Monitor
        uses: snyk/actions/python-3.10@master
        with:
          command: monitor
          args: --org=python-cli
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
