name: Snyk Monitor

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run snyk monitor
        uses: snyk/actions/python-3.10@master
        with:
          command: monitor
          args: --org=dylan-test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
